import {
  Activity,
  AppWindow,
  Archive,
  ArrowRightLeft,
  BadgeCheck,
  Ban,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Braces,
  Bug,
  CalendarClock,
  Check,
  CircleAlert,
  CircleCheck,
  CircleStop,
  CircleX,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Container,
  Copy,
  Cpu,
  Database,
  DatabaseBackup,
  Download,
  Eye,
  FileCode,
  FileKey,
  FileText,
  Fingerprint,
  Flag,
  Folder,
  FolderGit2,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  Globe,
  Hammer,
  HardDrive,
  HeartPulse,
  History,
  Hourglass,
  Inbox,
  Key,
  Laptop,
  Layers,
  LifeBuoy,
  Link,
  ListOrdered,
  Lock,
  LogIn,
  Mail,
  MemoryStick,
  Monitor,
  Moon,
  Network,
  Package,
  Pause,
  Pencil,
  Play,
  Plug,
  Power,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Route,
  Save,
  Scaling,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Skull,
  SlidersHorizontal,
  Split,
  Tag,
  Terminal,
  Timer,
  Trash2,
  TriangleAlert,
  Unplug,
  Upload,
  User,
  Users,
  Variable,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The icons a figure can name (`icon: 'box'`). Figures take names, not
 * components: their props cross the server → client boundary as plain data.
 * Add an icon here before you use a new name.
 */
export const figureIcons = {
  activity: Activity,
  alert: TriangleAlert,
  archive: Archive,
  ban: Ban,
  bell: Bell,
  book: BookOpen,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  branch: GitBranch,
  browser: AppWindow,
  bug: Bug,
  calendar: CalendarClock,
  certificate: BadgeCheck,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  commit: GitCommitHorizontal,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  backup: DatabaseBackup,
  deploy: CloudUpload,
  disk: HardDrive,
  download: Download,
  error: CircleX,
  eye: Eye,
  file: FileText,
  'file-code': FileCode,
  'file-key': FileKey,
  fingerprint: Fingerprint,
  flag: Flag,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  hammer: Hammer,
  health: HeartPulse,
  history: History,
  hourglass: Hourglass,
  inbox: Inbox,
  info: CircleAlert,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  lifebuoy: LifeBuoy,
  link: Link,
  lock: Lock,
  login: LogIn,
  logs: ScrollText,
  mail: Mail,
  memory: MemoryStick,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  ok: CircleCheck,
  package: Package,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  power: Power,
  pull: CloudDownload,
  queue: ListOrdered,
  repeat: Repeat,
  repo: FolderGit2,
  restart: RefreshCw,
  rocket: Rocket,
  rollback: RotateCcw,
  route: Route,
  save: Save,
  scale: Scaling,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  ship: Ship,
  skull: Skull,
  sliders: SlidersHorizontal,
  split: Split,
  stop: CircleStop,
  switch: ArrowRightLeft,
  tag: Tag,
  terminal: Terminal,
  timer: Timer,
  trash: Trash2,
  unplug: Unplug,
  upload: Upload,
  user: User,
  users: Users,
  variable: Variable,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type FigureIcon = keyof typeof figureIcons;

/** The icon for a name, or `undefined` for an unknown name (the figure then shows no icon). */
export function figureIcon(name: string | undefined): LucideIcon | undefined {
  return name ? (figureIcons as Record<string, LucideIcon>)[name] : undefined;
}
