import { source } from '@/lib/source';
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
  EditOnGitHub,
  MarkdownCopyButton,
} from 'fumadocs-ui/layouts/notebook/page';
import { notFound } from 'next/navigation';
import { getMDXComponents } from '@/components/mdx';
import { OpenAPIPage } from '@/components/api-page';
import type { Metadata } from 'next';
import type { OpenAPIPageProps } from 'fumadocs-openapi/ui';
import { createRelativeLink } from 'fumadocs-ui/mdx';
import { openapi } from '@/lib/openapi';
import { getPageImageUrl, getPageMarkdownUrl, gitConfig, githubUrl } from '@/lib/shared';

export default async function Page(props: PageProps<'/docs/[[...slug]]'>) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;
  const markdownUrl = getPageMarkdownUrl(page).url;
  // Generated API reference pages carry `_openapi` frontmatter: preload their schema.
  const openapiProps = page.data._openapi ? await openapi.preloadOpenAPIPage(page) : undefined;
  const isApiPage = Boolean(page.data._openapi);
  // Generated by scripts/generate.mjs: fix the source (Rust help text / OpenAPI), not the page.
  const isGenerated =
    page.path.startsWith('reference/api/') ||
    page.path === 'reference/cli.mdx' ||
    page.path === 'reference/server-options.mdx';

  return (
    <DocsPage
      toc={page.data.toc}
      full={page.data.full}
      tableOfContent={{ style: 'clerk' }}
      className={isApiPage ? undefined : '*:max-w-[760px]'}
    >
      <DocsTitle className="text-[28px] leading-tight font-medium tracking-[-0.015em]">{page.data.title}</DocsTitle>
      <DocsDescription className="mb-0 text-[16px] leading-relaxed text-foreground-light">
        {page.data.description}
      </DocsDescription>
      <div className="flex flex-row flex-wrap items-center gap-2 border-b border-border pb-5">
        <MarkdownCopyButton markdownUrl={markdownUrl} />
        {isGenerated ? null : (
          <EditOnGitHub href={`${githubUrl}/blob/${gitConfig.branch}/docs/content/docs/${page.path}`} />
        )}
      </div>
      <DocsBody>
        <MDX
          components={getMDXComponents({
            // Link to other pages with relative file paths: [Deploys](./deploys.mdx)
            a: createRelativeLink(source, page),
            OpenAPIPage: (apiProps: OpenAPIPageProps) => <OpenAPIPage {...apiProps} {...openapiProps} />,
          })}
        />
      </DocsBody>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(props: PageProps<'/docs/[[...slug]]'>): Promise<Metadata> {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const image = getPageImageUrl(page).url;
  return {
    title: page.data.title,
    description: page.data.description,
    openGraph: { title: page.data.title, description: page.data.description, images: image },
    twitter: { card: 'summary_large_image', title: page.data.title, description: page.data.description, images: image },
  };
}
