//! Responses generated by the proxy itself: branded error pages, HTTPS
//! redirects and ACME HTTP-01 answers.

use bytes::Bytes;
use http::header::{CACHE_CONTROL, CONTENT_LENGTH, CONTENT_TYPE, HeaderValue, LOCATION, RETRY_AFTER};
use http::{HeaderName, Response, StatusCode};

use crate::body::{self, ProxyBody};

/// Header naming the kind of proxy-generated error (lets clients and tests
/// tell a Ferry error page apart from an app's own 404/502).
pub(crate) const X_FERRY_ERROR: HeaderName = HeaderName::from_static("x-ferry-error");

/// Every error the proxy answers by itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ErrorKind {
    /// Missing / malformed `Host`.
    BadRequest,
    /// No route for the host (or unknown ACME token).
    NotFound,
    /// Methods a reverse proxy doesn't forward (`CONNECT`).
    MethodNotAllowed,
    /// The client stopped sending its request body.
    RequestTimeout,
    /// The service is suspended.
    Suspended,
    /// The service has no healthy instance yet.
    NoUpstreams,
    /// The upstream refused the connection or failed mid-request.
    BadGateway,
}

impl ErrorKind {
    pub(crate) fn status(self) -> StatusCode {
        match self {
            ErrorKind::BadRequest => StatusCode::BAD_REQUEST,
            ErrorKind::NotFound => StatusCode::NOT_FOUND,
            ErrorKind::MethodNotAllowed => StatusCode::METHOD_NOT_ALLOWED,
            ErrorKind::RequestTimeout => StatusCode::REQUEST_TIMEOUT,
            ErrorKind::Suspended | ErrorKind::NoUpstreams => StatusCode::SERVICE_UNAVAILABLE,
            ErrorKind::BadGateway => StatusCode::BAD_GATEWAY,
        }
    }

    /// Value of the `x-ferry-error` header.
    pub(crate) fn code(self) -> &'static str {
        match self {
            ErrorKind::BadRequest => "bad_request",
            ErrorKind::NotFound => "not_found",
            ErrorKind::MethodNotAllowed => "method_not_allowed",
            ErrorKind::RequestTimeout => "request_timeout",
            ErrorKind::Suspended => "suspended",
            ErrorKind::NoUpstreams => "no_upstreams",
            ErrorKind::BadGateway => "bad_gateway",
        }
    }
}

/// Branded HTML error page. `message` is plain text (escaped here); `head`
/// suppresses the body for `HEAD` requests.
pub(crate) fn error_page(kind: ErrorKind, message: &str, head: bool) -> Response<ProxyBody> {
    let status = kind.status();
    let html = render_page(status, message);
    let mut builder = Response::builder()
        .status(status)
        .header(CONTENT_TYPE, "text/html; charset=utf-8")
        .header(CACHE_CONTROL, "no-store")
        .header(X_FERRY_ERROR, kind.code());
    if kind == ErrorKind::NoUpstreams {
        builder = builder.header(RETRY_AFTER, "5");
    }
    if kind == ErrorKind::MethodNotAllowed {
        builder = builder.header(http::header::ALLOW, "GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS");
    }
    finish(builder, html, head)
}

/// `308 Permanent Redirect` to `location` (already a valid URL).
pub(crate) fn redirect(location: HeaderValue, head: bool) -> Response<ProxyBody> {
    let builder = Response::builder()
        .status(StatusCode::PERMANENT_REDIRECT)
        .header(LOCATION, location)
        .header(CONTENT_TYPE, "text/plain; charset=utf-8");
    finish(builder, "Redirecting to HTTPS\n", head)
}

/// `200 text/plain` with an ACME HTTP-01 key authorization.
pub(crate) fn acme_answer(key_authorization: String, head: bool) -> Response<ProxyBody> {
    let builder =
        Response::builder().status(StatusCode::OK).header(CONTENT_TYPE, "text/plain").header(CACHE_CONTROL, "no-store");
    finish(builder, key_authorization, head)
}

/// Attach `content`, or for `HEAD` only its `Content-Length` (RFC 9110 §9.3.2).
fn finish(builder: http::response::Builder, content: impl Into<Bytes>, head: bool) -> Response<ProxyBody> {
    let content = content.into();
    let body = if head {
        builder.header(CONTENT_LENGTH, content.len()).body(body::empty())
    } else {
        builder.body(body::full(content))
    };
    // Only static, known-valid header names/values are used by the callers, so
    // the builder cannot fail; fall back to a bare 500 rather than panicking.
    body.unwrap_or_else(|e| {
        tracing::error!("proxy: building a response failed: {e}");
        let mut resp = Response::new(body::empty());
        *resp.status_mut() = StatusCode::INTERNAL_SERVER_ERROR;
        resp
    })
}

fn render_page(status: StatusCode, message: &str) -> String {
    let code = status.as_u16();
    let reason = status.canonical_reason().unwrap_or("Error");
    let message = escape_html(message);
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta name="robots" content="noindex">
<title>{code} {reason} · Ferry</title>
<style>
:root{{--bg:#f5f6f8;--card:#fff;--fg:#1b2230;--muted:#5b6576;--accent:#2f5bd3;--line:#e1e5eb}}
@media (prefers-color-scheme:dark){{:root{{--bg:#0e1116;--card:#161b22;--fg:#e6e9ef;--muted:#99a3b3;--accent:#86a2ff;--line:#29303a}}}}
*{{box-sizing:border-box}}
body{{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px 16px;background:var(--bg);color:var(--fg);font:16px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}}
main{{width:100%;max-width:520px;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:32px}}
.code{{font-size:56px;font-weight:700;line-height:1;letter-spacing:-.02em;color:var(--accent);font-variant-numeric:tabular-nums}}
h1{{font-size:20px;margin:14px 0 6px}}
p{{margin:0;color:var(--muted);overflow-wrap:anywhere}}
footer{{margin-top:28px;padding-top:14px;border-top:1px solid var(--line);font-size:13px;color:var(--muted)}}
footer b{{color:var(--fg);font-weight:600}}
</style>
</head>
<body>
<main>
<div class="code">{code}</div>
<h1>{reason}</h1>
<p>{message}</p>
<footer>Served by <b>Ferry</b></footer>
</main>
</body>
</html>
"#
    )
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use http_body_util::BodyExt;

    use super::*;

    async fn body_text(resp: Response<ProxyBody>) -> String {
        let bytes = resp.into_body().collect().await.unwrap().to_bytes();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    #[tokio::test]
    async fn error_page_is_branded_and_escaped() {
        let resp = error_page(ErrorKind::NotFound, "No service is configured for <script>&\"'", false);
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
        assert_eq!(resp.headers()[CONTENT_TYPE], "text/html; charset=utf-8");
        assert_eq!(resp.headers()[X_FERRY_ERROR], "not_found");
        assert!(resp.headers().get(RETRY_AFTER).is_none());
        let html = body_text(resp).await;
        assert!(html.contains("Ferry"));
        assert!(html.contains("404"));
        assert!(html.contains("Not Found"));
        assert!(html.contains("prefers-color-scheme:dark"));
        assert!(html.contains("No service is configured for &lt;script&gt;&amp;&quot;&#39;"));
        assert!(!html.contains("<script>"));
    }

    #[tokio::test]
    async fn no_upstreams_has_retry_after_and_head_has_no_body() {
        let get_len = body_text(error_page(ErrorKind::NoUpstreams, "x", false)).await.len();
        let resp = error_page(ErrorKind::NoUpstreams, "x", true);
        assert_eq!(resp.status(), StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(resp.headers()[RETRY_AFTER], "5");
        assert_eq!(resp.headers()[CONTENT_LENGTH], get_len.to_string().as_str());
        assert_eq!(resp.headers()[X_FERRY_ERROR], "no_upstreams");
        assert_eq!(body_text(resp).await, "");
    }

    #[tokio::test]
    async fn redirect_and_acme() {
        let resp = redirect(HeaderValue::from_static("https://a.test/x?y=1"), false);
        assert_eq!(resp.status(), StatusCode::PERMANENT_REDIRECT);
        assert_eq!(resp.headers()[LOCATION], "https://a.test/x?y=1");
        let resp = acme_answer("tok.thumb".into(), false);
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(resp.headers()[CONTENT_TYPE], "text/plain");
        assert_eq!(body_text(resp).await, "tok.thumb");
    }

    #[test]
    fn kinds_map_to_statuses() {
        assert_eq!(ErrorKind::BadRequest.status(), 400);
        assert_eq!(ErrorKind::MethodNotAllowed.status(), 405);
        assert_eq!(ErrorKind::RequestTimeout.status(), 408);
        assert_eq!(ErrorKind::RequestTimeout.code(), "request_timeout");
        assert_eq!(ErrorKind::Suspended.status(), 503);
        assert_eq!(ErrorKind::BadGateway.status(), 502);
        assert_eq!(ErrorKind::BadGateway.code(), "bad_gateway");
    }
}
