//! Embeds the web client (`web/dist`, built with `cd web && npm ci && npm run
//! build`) into the crate: every file becomes an entry of a static table in
//! `$OUT_DIR/web_assets.rs` (`include_bytes!` of the file itself, so rustc
//! also tracks the files). `FERRY_WEB_DIST` overrides the directory.
//!
//! Without a built client (no `index.html`), a small placeholder page that
//! explains how to build it is embedded instead, so the Rust workspace never
//! needs Node to compile.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

const PLACEHOLDER: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="ferry-ui" content="placeholder">
<title>Ferry</title>
<style>
  :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
  body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: Canvas; color: CanvasText; }
  main { max-width: 36rem; padding: 2rem; line-height: 1.5; }
  h1 { font-size: 1.25rem; margin: 0 0 .75rem; }
  pre { padding: .75rem 1rem; border-radius: 6px; background: color-mix(in srgb, CanvasText 8%, Canvas); overflow-x: auto; }
  p { opacity: .85; }
</style>
</head>
<body>
<main>
  <h1>The Ferry dashboard isn't built into this server</h1>
  <p>The web client lives in <code>web/</code> and is embedded when <code>ferry-api</code> compiles. Build it, then rebuild the server:</p>
  <pre>cd web &amp;&amp; npm ci &amp;&amp; npm run build
cargo build -p ferryd</pre>
  <p>Or point a running server at a built client with <code>FERRY_UI_DIR=/path/to/web/dist</code>. The REST API and the <code>ferry</code> CLI work either way.</p>
</main>
</body>
</html>
"#;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=FERRY_WEB_DIST");

    let web_dir = manifest_dir.join("../../web");
    let dist = match env::var_os("FERRY_WEB_DIST").filter(|v| !v.is_empty()) {
        Some(d) => PathBuf::from(d),
        None => web_dir.join("dist"),
    };

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if dist.join("index.html").is_file() {
        // Rerun when anything in dist changes (cargo scans directories
        // recursively), and for every embedded file.
        println!("cargo:rerun-if-changed={}", dist.display());
        collect(&dist, &dist, &mut files);
        for (_, path) in &files {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    } else {
        // Never watch a missing path: cargo would rerun this script (and
        // rebuild the crate) on every build. Watch the client's project
        // instead, so building it later is picked up.
        if web_dir.is_dir() {
            println!("cargo:rerun-if-changed={}", web_dir.display());
        }
        println!(
            "cargo:warning=web client not built ({} has no index.html): embedding a placeholder page. Build it with `cd web && npm ci && npm run build`.",
            dist.display()
        );
        let placeholder = out_dir.join("placeholder-index.html");
        fs::write(&placeholder, PLACEHOLDER).expect("writing the placeholder page");
        files.push(("index.html".to_string(), placeholder));
    }
    files.sort();

    let mut code = String::new();
    code.push_str("// Generated by build.rs: the embedded web client.\n\n");
    let _ = writeln!(code, "/// True when `web/dist` wasn't built and a placeholder page is embedded.");
    let _ = writeln!(code, "pub const PLACEHOLDER: bool = {};", !dist.join("index.html").is_file());
    code.push_str("\n/// `(path relative to dist, '/'-separated; ETag; bytes)`, sorted by path.\n");
    code.push_str("pub static FILES: &[(&str, &str, &[u8])] = &[\n");
    for (rel, path) in &files {
        let bytes = fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        let abs = path.canonicalize().unwrap_or_else(|_| path.clone());
        let etag = format!("\"{:016x}-{:x}\"", fnv1a(&bytes), bytes.len());
        let _ = writeln!(code, "    ({rel:?}, {etag:?}, include_bytes!({:?})),", abs.display().to_string());
    }
    code.push_str("];\n");
    fs::write(out_dir.join("web_assets.rs"), code).expect("writing web_assets.rs");
}

/// Every regular file below `dir` as (`/`-separated path relative to `root`, path).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = fs::read_dir(dir).unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()));
        let path = entry.path();
        let name = entry.file_name();
        if name == ".DS_Store" {
            continue;
        }
        let meta = fs::metadata(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        if meta.is_dir() {
            collect(root, &path, out);
        } else if meta.is_file() {
            let rel = path.strip_prefix(root).expect("below the root");
            let rel: Vec<String> = rel.components().map(|c| c.as_os_str().to_string_lossy().into_owned()).collect();
            out.push((rel.join("/"), path));
        }
    }
}

/// FNV-1a (64 bit): a cheap content hash for ETags.
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}
