//! Dockerfile generation for native runtimes (Nixpacks-style, small official
//! base images, dependency layers cached separately from the source).

use std::path::Path;

use ferry_core::{Error, Result, Runtime, ServiceType};
use serde_json::Value;

use crate::detect::{self, CargoInfo, node_major_for, read_text};
use crate::{DockerfileOptions, GeneratedDockerfile};

pub(crate) const DEFAULT_PYTHON: &str = "3.12";
pub(crate) const DEFAULT_GO: &str = "1.23";
pub(crate) const DEFAULT_RUBY: &str = "3.3";
const NGINX_HTML: &str = "/usr/share/nginx/html";

/// Entry point behind [`crate::generate_dockerfile`].
pub(crate) fn generate(runtime: Runtime, dir: &Path, opts: &DockerfileOptions) -> Result<GeneratedDockerfile> {
    let runtime = match runtime {
        Runtime::Auto => detect::detect(dir).ok_or_else(|| {
            Error::invalid("could not detect the runtime: no Dockerfile or known project manifest found")
        })?,
        r => r,
    };
    if runtime == Runtime::Static || opts.service_type == Some(ServiceType::StaticSite) {
        return static_site(dir, opts);
    }
    let contents = match runtime {
        Runtime::Node => node(dir, opts)?,
        Runtime::Python => python(dir, opts)?,
        Runtime::Go => go(dir, opts)?,
        Runtime::Rust => rust(dir, opts)?,
        Runtime::Ruby => ruby(dir, opts)?,
        Runtime::Docker | Runtime::Image | Runtime::Auto | Runtime::Static => {
            return Err(Error::invalid(format!("no Dockerfile generator for runtime '{runtime}'")));
        }
    };
    Ok(GeneratedDockerfile { contents, port_hint: None })
}

// ---------------------------------------------------------------------------
// Dockerfile writer

/// Build-arg names that are safe to declare (`ARG NAME`) and that do not
/// clobber variables every build step relies on.
pub(crate) fn usable_build_arg(key: &str) -> bool {
    let mut chars = key.chars();
    let valid = matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && key.len() <= 256;
    valid && !is_reserved_build_arg(key)
}

fn is_reserved_build_arg(key: &str) -> bool {
    const EXACT: &[&str] = &[
        "PATH",
        "HOME",
        "PWD",
        "OLDPWD",
        "HOSTNAME",
        "SHELL",
        "USER",
        "LOGNAME",
        "TERM",
        "SHLVL",
        "TMPDIR",
        "LD_PRELOAD",
        "LD_LIBRARY_PATH",
        "SSH_AUTH_SOCK",
    ];
    const PREFIXES: &[&str] = &["DOCKER_", "BUILDKIT_", "BUILDX_", "COMPOSE_", "XDG_"];
    EXACT.contains(&key) || PREFIXES.iter().any(|p| key.starts_with(p))
}

/// `RUN ` plus build flags, one per continuation line for readability.
fn run_prefix(flags: &[String]) -> String {
    if flags.is_empty() { "RUN ".to_string() } else { format!("RUN {} \\\n    ", flags.join(" \\\n    ")) }
}

/// Can `cmd` be written as a shell-form instruction on one Dockerfile line?
fn shell_form_ok(cmd: &str) -> bool {
    !cmd.contains('\n') && !cmd.contains('\r') && !cmd.contains("<<") && !cmd.trim_end().ends_with('\\')
}

fn json(v: &[&str]) -> String {
    serde_json::to_string(v).unwrap_or_else(|_| "[]".to_string())
}

#[derive(Default)]
struct Df {
    lines: Vec<String>,
}

impl Df {
    fn new(header: &str) -> Self {
        let mut d = Df::default();
        d.line(format!("# Generated by Ferry: {header}."));
        d.line("# Commit your own Dockerfile to customize the build.");
        d
    }

    fn line(&mut self, s: impl Into<String>) {
        self.lines.push(s.into());
    }

    fn blank(&mut self) {
        if self.lines.last().is_some_and(|l| !l.is_empty()) {
            self.lines.push(String::new());
        }
    }

    fn args(&mut self, keys: &[String]) {
        let mut seen: Vec<&str> = Vec::new();
        for k in keys {
            if usable_build_arg(k) && !seen.contains(&k.as_str()) {
                seen.push(k);
                self.line(format!("ARG {k}"));
            }
        }
    }

    /// `RUN` a (possibly user-supplied) command, with optional `--mount` flags.
    fn run(&mut self, flags: &[String], cmd: &str) {
        if shell_form_ok(cmd) {
            self.line(format!("{}{}", run_prefix(flags), cmd.trim()));
        } else {
            self.line(format!("{}{}", run_prefix(flags), json(&["/bin/sh", "-c", cmd])));
        }
    }

    /// `RUN` a sequence of steps; `user` marks user-supplied commands, which
    /// are isolated in a subshell so their own `;`/`||` can't change the chain.
    /// Multi-line commands (or ones with `#` comments) become a `set -e` script.
    fn run_steps(&mut self, flags: &[String], steps: &[(bool, String)]) {
        let chainable = steps.iter().all(|(user, s)| shell_form_ok(s) && !(*user && s.contains('#')));
        if chainable {
            let chain: Vec<String> =
                steps.iter().map(|(user, s)| if *user { format!("( {} )", s.trim()) } else { s.clone() }).collect();
            self.run(flags, &chain.join(" && "));
        } else {
            let mut script = String::from("set -e\n");
            for (_, s) in steps {
                script.push_str(s.trim_end());
                script.push('\n');
            }
            self.line(format!("{}{}", run_prefix(flags), json(&["/bin/sh", "-c", &script])));
        }
    }

    /// Start command run by a shell (so `$PORT` and friends expand). Written
    /// as `["/bin/sh","-c",…]`: exactly what Docker turns shell-form CMD into,
    /// but safe for any characters and free of BuildKit's JSONArgs warning.
    fn cmd_shell(&mut self, cmd: &str) {
        self.line(format!("CMD {}", json(&["/bin/sh", "-c", cmd.trim()])));
    }

    fn cmd_exec(&mut self, argv: &[&str]) {
        self.line(format!("CMD {}", json(argv)));
    }

    fn finish(mut self) -> String {
        while self.lines.last().is_some_and(|l| l.is_empty()) {
            self.lines.pop();
        }
        let mut s = self.lines.join("\n");
        s.push('\n');
        s
    }
}

fn nonempty(s: &Option<String>) -> Option<&str> {
    s.as_deref().map(str::trim).filter(|s| !s.is_empty())
}

fn exists(dir: &Path, name: &str) -> bool {
    dir.join(name).exists()
}

/// Where the start command comes from.
enum Start {
    Shell(String),
    Exec(Vec<String>),
    /// No command (cron jobs get their command at run time).
    None,
}

fn emit_start(df: &mut Df, start: Start) {
    match start {
        Start::Shell(c) => df.cmd_shell(&c),
        Start::Exec(argv) => {
            let refs: Vec<&str> = argv.iter().map(String::as_str).collect();
            df.cmd_exec(&refs);
        }
        Start::None => {}
    }
}

fn missing_start(what: &str, hint: &str, opts: &DockerfileOptions) -> Result<Start> {
    if opts.service_type == Some(ServiceType::CronJob) {
        return Ok(Start::None);
    }
    let entry = match opts.service_type {
        Some(ServiceType::BackgroundWorker) => "worker",
        _ => "web",
    };
    Err(Error::invalid(format!(
        "cannot determine how to start this {what} app: set a start command, add a Procfile with a `{entry}:` entry{hint}"
    )))
}

// ---------------------------------------------------------------------------
// Node.js

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Pm {
    Npm,
    Yarn,
    YarnBerry,
    Pnpm,
    Bun,
}

impl Pm {
    fn name(self) -> &'static str {
        match self {
            Pm::Npm => "npm",
            Pm::Yarn | Pm::YarnBerry => "yarn",
            Pm::Pnpm => "pnpm",
            Pm::Bun => "bun",
        }
    }

    fn run_script(self, script: &str) -> String {
        format!("{} run {script}", self.name())
    }
}

struct NodePlan {
    pm: Pm,
    base_image: String,
    install: String,
    manifests: Vec<&'static str>,
    copy_yarn_dir: bool,
    copy_all_first: bool,
    has_build_script: bool,
    has_start_script: bool,
    main: Option<String>,
}

const NODE_MANIFESTS: &[&str] = &[
    "package.json",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "bun.lock",
    ".npmrc",
    ".yarnrc",
    ".yarnrc.yml",
    ".pnpmfile.cjs",
    "pnpm-workspace.yaml",
    "bunfig.toml",
];

fn read_package_json(dir: &Path) -> Result<Option<Value>> {
    match read_text(dir, "package.json") {
        None => Ok(None),
        Some(s) => serde_json::from_str::<Value>(&s)
            .map(Some)
            .map_err(|e| Error::invalid(format!("package.json is not valid JSON: {e}"))),
    }
}

fn script<'a>(pkg: &'a Value, name: &str) -> Option<&'a str> {
    pkg.get("scripts")?.get(name)?.as_str().map(str::trim).filter(|s| !s.is_empty())
}

fn node_plan(dir: &Path) -> Result<NodePlan> {
    let pkg = read_package_json(dir)?;
    let empty = Value::Object(Default::default());
    let p = pkg.as_ref().unwrap_or(&empty);
    let has = |f: &str| dir.join(f).is_file();

    let field = p.get("packageManager").and_then(Value::as_str).unwrap_or("").trim().to_string();
    let field_major = |name: &str| -> Option<u32> {
        let v = field.strip_prefix(name)?.strip_prefix('@')?;
        v.split('.').next()?.parse().ok()
    };
    let berry_markers = has(".yarnrc.yml")
        || read_text(dir, "yarn.lock").is_some_and(|l| l.contains("__metadata:"))
        || field_major("yarn").is_some_and(|m| m >= 2);
    let pm = if field.starts_with("pnpm@") {
        Pm::Pnpm
    } else if field.starts_with("yarn@") {
        if berry_markers { Pm::YarnBerry } else { Pm::Yarn }
    } else if field.starts_with("bun@") {
        Pm::Bun
    } else if field.starts_with("npm@") {
        Pm::Npm
    } else if has("bun.lockb") || has("bun.lock") {
        Pm::Bun
    } else if has("pnpm-lock.yaml") {
        Pm::Pnpm
    } else if has("yarn.lock") {
        if berry_markers { Pm::YarnBerry } else { Pm::Yarn }
    } else {
        Pm::Npm
    };

    let install = match pm {
        Pm::Npm if has("package-lock.json") || has("npm-shrinkwrap.json") => {
            "npm ci --include=dev --no-audit --no-fund"
        }
        Pm::Npm => "npm install --include=dev --no-audit --no-fund",
        Pm::Yarn if has("yarn.lock") => "yarn install --frozen-lockfile --production=false",
        Pm::Yarn => "yarn install --production=false",
        Pm::YarnBerry if has("yarn.lock") => "yarn install --immutable",
        Pm::YarnBerry => "yarn install",
        Pm::Pnpm if has("pnpm-lock.yaml") => "pnpm install --frozen-lockfile",
        Pm::Pnpm => "pnpm install",
        Pm::Bun => "bun install",
    }
    .to_string();

    let major = node_major_for(p.get("engines").and_then(|e| e.get("node")).and_then(Value::as_str));
    let base_image = if pm == Pm::Bun { "oven/bun:1-alpine".to_string() } else { format!("node:{major}-alpine") };

    // Installing from the manifests alone breaks when install needs other
    // files: workspaces, lifecycle scripts, local dependencies.
    let lifecycle = ["preinstall", "install", "postinstall", "prepare"].iter().any(|s| script(p, s).is_some());
    let local_deps = ["dependencies", "devDependencies", "optionalDependencies"].iter().any(|k| {
        p.get(*k).and_then(Value::as_object).is_some_and(|deps| {
            deps.values()
                .filter_map(Value::as_str)
                .any(|v| ["file:", "link:", "portal:", "workspace:"].iter().any(|pre| v.trim_start().starts_with(pre)))
        })
    });
    let copy_all_first =
        pkg.is_none() || p.get("workspaces").is_some() || has("pnpm-workspace.yaml") || lifecycle || local_deps;

    let manifests: Vec<&'static str> = NODE_MANIFESTS.iter().copied().filter(|f| has(f)).collect();
    let copy_yarn_dir = pm == Pm::YarnBerry && dir.join(".yarn").is_dir();
    let main = p.get("main").and_then(Value::as_str).map(str::trim).filter(|m| !m.is_empty()).map(str::to_string);

    Ok(NodePlan {
        pm,
        base_image,
        install,
        manifests,
        copy_yarn_dir,
        copy_all_first,
        has_build_script: script(p, "build").is_some(),
        has_start_script: script(p, "start").is_some(),
        main,
    })
}

/// FROM … through the build step, shared by Node apps and node-built static sites.
fn node_build_stage(df: &mut Df, plan: &NodePlan, stage: Option<&str>, build: Option<&str>, opts: &DockerfileOptions) {
    match stage {
        Some(name) => df.line(format!("FROM {} AS {name}", plan.base_image)),
        None => df.line(format!("FROM {}", plan.base_image)),
    }
    df.line("WORKDIR /app");
    if matches!(plan.pm, Pm::Yarn | Pm::YarnBerry | Pm::Pnpm) {
        df.line("ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0");
        df.run(&[], "(corepack --version >/dev/null 2>&1 || npm install -g corepack) && corepack enable");
    }
    df.args(&opts.build_arg_keys);
    df.blank();
    if plan.copy_all_first || plan.manifests.is_empty() {
        df.line("COPY . .");
        df.run(&[], &plan.install);
    } else {
        df.line(format!("COPY {} ./", plan.manifests.join(" ")));
        if plan.copy_yarn_dir {
            df.line("COPY .yarn ./.yarn");
        }
        df.run(&[], &plan.install);
        df.blank();
        df.line("COPY . .");
    }
    // After install, so devDependencies needed by the build are installed.
    df.line("ENV NODE_ENV=production");
    if let Some(b) = build {
        df.run(&[], b);
    }
}

fn node(dir: &Path, opts: &DockerfileOptions) -> Result<String> {
    let plan = node_plan(dir)?;
    let build = nonempty(&opts.build_command)
        .map(str::to_string)
        .or_else(|| plan.has_build_script.then(|| plan.pm.run_script("build")));
    let start = if let Some(s) = nonempty(&opts.start_command) {
        Start::Shell(s.to_string())
    } else if let Some(p) = detect::procfile_command(dir, opts.service_type) {
        Start::Shell(p)
    } else if plan.has_start_script {
        Start::Exec(match plan.pm {
            Pm::YarnBerry => vec!["yarn".into(), "start".into()],
            Pm::Bun => vec!["bun".into(), "run".into(), "start".into()],
            _ => vec!["npm".into(), "start".into()],
        })
    } else if let Some(entry) =
        plan.main.clone().filter(|m| build.is_some() || dir.join(m).is_file()).or_else(|| {
            ["server.js", "index.js", "app.js"].iter().find(|f| dir.join(f).is_file()).map(|f| f.to_string())
        })
    {
        Start::Exec(match plan.pm {
            Pm::YarnBerry => vec!["yarn".into(), "node".into(), entry],
            Pm::Bun => vec!["bun".into(), entry],
            _ => vec!["node".into(), entry],
        })
    } else {
        missing_start("Node.js", ", a \"start\" script to package.json, or a server.js / index.js file", opts)?
    };

    let mut df = Df::new(&format!("Node.js app ({})", plan.pm.name()));
    node_build_stage(&mut df, &plan, None, build.as_deref(), opts);
    df.blank();
    emit_start(&mut df, start);
    Ok(df.finish())
}

// ---------------------------------------------------------------------------
// Python

fn python(dir: &Path, opts: &DockerfileOptions) -> Result<String> {
    let version = detect::python_version(dir).unwrap_or_else(|| DEFAULT_PYTHON.to_string());
    let mut df = Df::new("Python app");
    df.line(format!("FROM python:{version}-slim"));
    df.line("ENV PYTHONUNBUFFERED=1 \\");
    df.line("    PYTHONDONTWRITEBYTECODE=1 \\");
    df.line("    PIP_DISABLE_PIP_VERSION_CHECK=1 \\");
    df.line("    PIP_ROOT_USER_ACTION=ignore");
    df.line("WORKDIR /app");
    df.args(&opts.build_arg_keys);
    df.blank();

    if dir.join("requirements.txt").is_file() {
        let reqs = read_text(dir, "requirements.txt").unwrap_or_default();
        // References to other files (-r, -c, -e ., local paths) need the full tree.
        let needs_tree = reqs.lines().map(str::trim).any(|l| {
            l.starts_with("-r")
                || l.starts_with("-c")
                || l.starts_with("-e")
                || l.starts_with("--requirement")
                || l.starts_with("--constraint")
                || l.starts_with("--editable")
                || l.starts_with('.')
                || l.starts_with("file:")
        });
        if needs_tree {
            df.line("COPY . .");
            df.run(&[], "pip install --no-cache-dir -r requirements.txt");
        } else {
            df.line("COPY requirements.txt ./");
            df.run(&[], "pip install --no-cache-dir -r requirements.txt");
            df.blank();
            df.line("COPY . .");
        }
    } else if dir.join("pyproject.toml").is_file() {
        df.line("COPY . .");
        df.run(&[], "pip install --no-cache-dir .");
    } else if dir.join("Pipfile").is_file() {
        let has_lock = dir.join("Pipfile.lock").is_file();
        df.line(if has_lock { "COPY Pipfile Pipfile.lock ./" } else { "COPY Pipfile ./" });
        df.run(
            &[],
            if has_lock {
                "pip install --no-cache-dir pipenv && pipenv install --system --deploy"
            } else {
                "pip install --no-cache-dir pipenv && pipenv install --system --skip-lock"
            },
        );
        df.blank();
        df.line("COPY . .");
    } else {
        df.line("COPY . .");
    }
    if let Some(b) = nonempty(&opts.build_command) {
        df.run(&[], b);
    }
    df.blank();

    let start = if let Some(s) = nonempty(&opts.start_command) {
        Start::Shell(s.to_string())
    } else if let Some(p) = detect::procfile_command(dir, opts.service_type) {
        Start::Shell(p)
    } else if let Some(f) = ["main.py", "app.py"].iter().find(|f| dir.join(f).is_file()) {
        Start::Exec(vec!["python".into(), f.to_string()])
    } else {
        missing_start("Python", ", or a main.py / app.py file", opts)?
    };
    emit_start(&mut df, start);
    Ok(df.finish())
}

// ---------------------------------------------------------------------------
// Go

/// Package to build: `.` when the root has Go files, else the single
/// directory under `cmd/`.
fn go_main_package(dir: &Path) -> String {
    let root_has_go = std::fs::read_dir(dir)
        .map(|rd| rd.flatten().any(|e| e.path().extension().is_some_and(|x| x == "go")))
        .unwrap_or(false);
    if root_has_go {
        return ".".to_string();
    }
    let cmds: Vec<String> = std::fs::read_dir(dir.join("cmd"))
        .map(|rd| {
            rd.flatten()
                .filter(|e| e.path().is_dir())
                .filter_map(|e| e.file_name().to_str().map(str::to_string))
                .filter(|n| n.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.')))
                .collect()
        })
        .unwrap_or_default();
    match cmds.as_slice() {
        [only] => format!("./cmd/{only}"),
        _ => ".".to_string(),
    }
}

fn go(dir: &Path, opts: &DockerfileOptions) -> Result<String> {
    let version = detect::go_version(dir).unwrap_or_else(|| DEFAULT_GO.to_string());
    let gomod = read_text(dir, "go.mod").unwrap_or_default();
    let local_replace = gomod.lines().any(|l| l.contains("=> ./") || l.contains("=> ../") || l.contains("=> /"));
    let vendored = dir.join("vendor").is_dir();
    let mod_cache = "--mount=type=cache,target=/go/pkg/mod".to_string();
    let build_cache = "--mount=type=cache,target=/root/.cache/go-build".to_string();

    let mut df = Df::new("Go app");
    df.line(format!("FROM golang:{version}-alpine AS build"));
    df.line("WORKDIR /src");
    df.args(&opts.build_arg_keys);
    df.blank();
    if exists(dir, "go.mod") && !local_replace && !vendored {
        df.line(if exists(dir, "go.sum") { "COPY go.mod go.sum ./" } else { "COPY go.mod ./" });
        df.run(std::slice::from_ref(&mod_cache), "go mod download");
        df.blank();
    }
    df.line("COPY . .");
    let steps: Vec<(bool, String)> = match nonempty(&opts.build_command) {
        Some(b) => vec![(false, "mkdir -p /out".into()), (true, b.to_string())],
        None => vec![
            (false, "mkdir -p /out".into()),
            (
                false,
                format!("CGO_ENABLED=0 go build -trimpath -ldflags=\"-s -w\" -o /out/app {}", go_main_package(dir)),
            ),
        ],
    };
    df.run_steps(&[mod_cache, build_cache], &steps);
    df.blank();
    df.line("FROM alpine:3.20");
    df.run(&[], "apk add --no-cache ca-certificates tzdata");
    df.line("WORKDIR /app");
    // The source tree stays available for runtime assets (templates, static
    // files) and Render-style start commands such as `./app`.
    df.line("COPY --from=build /src/ /app/");
    df.line("COPY --from=build /out/ /usr/local/bin/");
    df.blank();
    let start = if let Some(s) = nonempty(&opts.start_command) {
        Start::Shell(s.to_string())
    } else if let Some(p) = detect::procfile_command(dir, opts.service_type) {
        Start::Shell(p)
    } else {
        Start::Exec(vec!["/usr/local/bin/app".into()])
    };
    emit_start(&mut df, start);
    Ok(df.finish())
}

// ---------------------------------------------------------------------------
// Rust

fn rust(dir: &Path, opts: &DockerfileOptions) -> Result<String> {
    let info: CargoInfo = detect::parse_cargo_toml(&read_text(dir, "Cargo.toml").unwrap_or_default());
    let bin = detect::rust_binary(dir, &info);
    if let Some(b) = &bin
        && !b.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(Error::invalid(format!("unsupported Rust binary name '{b}'")));
    }
    let start_command = nonempty(&opts.start_command).map(str::to_string);
    let procfile = detect::procfile_command(dir, opts.service_type);
    if bin.is_none() && start_command.is_none() && procfile.is_none() && opts.service_type != Some(ServiceType::CronJob)
    {
        return Err(Error::invalid(
            "cannot determine which binary to run (Cargo workspace without a root package): set a start command \
             naming the binary; release binaries are installed in /usr/local/bin",
        ));
    }
    let needs_openssl = read_text(dir, "Cargo.lock").is_some_and(|l| l.contains("name = \"openssl-sys\""));
    let cache_id: String = info
        .package_name
        .as_deref()
        .or(bin.as_deref())
        .unwrap_or("workspace")
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect();

    let mut df = Df::new("Rust app");
    df.line("FROM rust:1-slim-bookworm AS build");
    if needs_openssl {
        df.run(
            &[],
            "apt-get update && apt-get install -y --no-install-recommends pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*",
        );
    }
    df.line("WORKDIR /src");
    df.args(&opts.build_arg_keys);
    df.blank();
    df.line("COPY . .");
    let mut steps: Vec<(bool, String)> = vec![
        // Sources must look newer than outputs in the cached target dir.
        (false, "find . -path ./target -prune -o -type f -exec touch {} +".into()),
    ];
    match nonempty(&opts.build_command) {
        Some(b) => steps.push((true, b.to_string())),
        None => steps.push((false, "cargo build --release".into())),
    }
    steps.push((false, "mkdir -p /out".into()));
    match &bin {
        Some(b) => steps.push((false, format!("cp target/release/{b} /out/"))),
        None => steps.push((false, "find target/release -maxdepth 1 -type f -perm -u+x -exec cp {} /out/ \\;".into())),
    }
    df.run_steps(
        &[
            "--mount=type=cache,target=/usr/local/cargo/registry,sharing=locked".to_string(),
            "--mount=type=cache,target=/usr/local/cargo/git,sharing=locked".to_string(),
            format!("--mount=type=cache,target=/src/target,id=ferry-cargo-target-{cache_id},sharing=locked"),
        ],
        &steps,
    );
    df.blank();
    df.line("FROM debian:bookworm-slim");
    let runtime_pkgs = if needs_openssl { "ca-certificates libssl3" } else { "ca-certificates" };
    df.run(
        &[],
        &format!(
            "apt-get update && apt-get install -y --no-install-recommends {runtime_pkgs} && rm -rf /var/lib/apt/lists/*"
        ),
    );
    df.line("WORKDIR /app");
    df.line("COPY --from=build /src/ /app/");
    df.line("COPY --from=build /out/ /usr/local/bin/");
    df.blank();
    let start = match (start_command, procfile, bin) {
        (Some(s), _, _) => Start::Shell(s),
        (None, Some(p), _) => Start::Shell(p),
        (None, None, Some(b)) => Start::Exec(vec![format!("/usr/local/bin/{b}")]),
        (None, None, None) => Start::None,
    };
    emit_start(&mut df, start);
    Ok(df.finish())
}

// ---------------------------------------------------------------------------
// Ruby

fn ruby(dir: &Path, opts: &DockerfileOptions) -> Result<String> {
    let version = detect::ruby_version(dir).unwrap_or_else(|| DEFAULT_RUBY.to_string());
    let gemfile = read_text(dir, "Gemfile").unwrap_or_default();
    let needs_tree = gemfile
        .lines()
        .map(str::trim)
        .any(|l| !l.starts_with('#') && (l.starts_with("gemspec") || l.contains("path:") || l.contains(":path")));
    let mut df = Df::new("Ruby app");
    df.line(format!("FROM ruby:{version}-slim"));
    df.run(
        &[],
        "apt-get update && apt-get install -y --no-install-recommends build-essential git libyaml-dev pkg-config \
         && rm -rf /var/lib/apt/lists/*",
    );
    df.line("WORKDIR /app");
    df.args(&opts.build_arg_keys);
    df.blank();
    if needs_tree || !exists(dir, "Gemfile") {
        df.line("COPY . .");
        df.run(&[], "bundle install");
    } else {
        df.line(if exists(dir, "Gemfile.lock") { "COPY Gemfile Gemfile.lock ./" } else { "COPY Gemfile ./" });
        df.run(&[], "bundle install");
        df.blank();
        df.line("COPY . .");
    }
    if let Some(b) = nonempty(&opts.build_command) {
        df.run(&[], b);
    }
    df.blank();
    let start = if let Some(s) = nonempty(&opts.start_command) {
        Start::Shell(s.to_string())
    } else if let Some(p) = detect::procfile_command(dir, opts.service_type) {
        Start::Shell(p)
    } else if exists(dir, "config.ru") {
        Start::Shell("bundle exec rackup -o 0.0.0.0 -p ${PORT:-10000}".to_string())
    } else {
        missing_start("Ruby", ", or a config.ru for Rack apps", opts)?
    };
    emit_start(&mut df, start);
    Ok(df.finish())
}

// ---------------------------------------------------------------------------
// Static sites

const PUBLISH_CANDIDATES: &[&str] = &["dist", "build", "out", "public"];

fn nginx_config_lines() -> Vec<&'static str> {
    vec![
        "server {",
        "    listen 80;",
        "    server_name _;",
        "    root /usr/share/nginx/html;",
        "    index index.html index.htm;",
        "    absolute_redirect off;",
        "    gzip on;",
        "    gzip_vary on;",
        "    gzip_min_length 256;",
        "    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml application/manifest+json image/svg+xml;",
        "    location / {",
        "        try_files $uri $uri/ $uri.html =404;",
        "    }",
        "    error_page 404 /404.html;",
        "}",
    ]
}

/// Normalized, shell/Dockerfile-safe publish directory (`None` = context root).
fn publish_dir(opts: &DockerfileOptions) -> Result<Option<String>> {
    let Some(raw) = nonempty(&opts.publish_dir) else { return Ok(None) };
    let rel = crate::fsutil::normalize_relative("publish directory", raw).map_err(Error::invalid)?;
    let s = rel.to_string_lossy().replace('\\', "/");
    if s.is_empty() {
        return Ok(None);
    }
    if !s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/' | '@' | '+')) {
        return Err(Error::invalid(format!(
            "publish directory '{raw}' contains unsupported characters (use letters, digits, '.', '_', '-', '/')"
        )));
    }
    Ok(Some(s))
}

fn nginx_stage(df: &mut Df) {
    df.line("FROM nginx:alpine");
    let mut run = format!("RUN rm -rf {NGINX_HTML}/* \\\n && printf '%s\\n' \\\n");
    for l in nginx_config_lines() {
        run.push_str(&format!("    '{l}' \\\n"));
    }
    run.push_str("    > /etc/nginx/conf.d/default.conf");
    df.line(run);
}

fn static_site(dir: &Path, opts: &DockerfileOptions) -> Result<GeneratedDockerfile> {
    let publish = publish_dir(opts)?;
    let has_pkg = dir.join("package.json").is_file();
    let plan = if has_pkg { Some(node_plan(dir)?) } else { None };
    let build = nonempty(&opts.build_command)
        .map(str::to_string)
        .or_else(|| plan.as_ref().filter(|p| p.has_build_script).map(|p| p.pm.run_script("build")));

    let mut df = Df::new("static site served by nginx");
    match build {
        Some(build) => {
            let plan = match plan {
                Some(p) => p,
                // A build command without package.json: run it in a Node image.
                None => NodePlan {
                    pm: Pm::Npm,
                    base_image: format!("node:{}-alpine", detect::DEFAULT_NODE_MAJOR),
                    install: String::new(),
                    manifests: Vec::new(),
                    copy_yarn_dir: false,
                    copy_all_first: true,
                    has_build_script: false,
                    has_start_script: false,
                    main: None,
                },
            };
            if plan.install.is_empty() {
                df.line(format!("FROM {} AS build", plan.base_image));
                df.line("WORKDIR /app");
                df.args(&opts.build_arg_keys);
                df.blank();
                df.line("COPY . .");
                df.line("ENV NODE_ENV=production");
                df.run(&[], &build);
            } else {
                node_build_stage(&mut df, &plan, Some("build"), Some(&build), opts);
            }
            // The output directory only exists after the build: pick it then.
            let select = match &publish {
                Some(p) => format!(
                    "mkdir -p /ferry-publish && if [ -d \"{p}\" ]; then cp -a \"{p}/.\" /ferry-publish/; \
                     else echo \"error: publish directory '{p}' not found after the build\" >&2; exit 1; fi"
                ),
                None => {
                    let list = PUBLISH_CANDIDATES.join(" ");
                    format!(
                        "mkdir -p /ferry-publish && for d in {list}; do if [ -d \"$d\" ]; then \
                         echo \"Publishing ./$d\"; cp -a \"$d/.\" /ferry-publish/; exit 0; fi; done; \
                         echo \"error: no build output found (looked for {list}); set the publish directory\" >&2; exit 1"
                    )
                }
            };
            df.run(&[], &select);
            df.blank();
            nginx_stage(&mut df);
            df.line(format!("COPY --from=build /ferry-publish/ {NGINX_HTML}/"));
        }
        None => {
            nginx_stage(&mut df);
            // No build step: an explicit publish dir, else the context root when
            // it holds index.html, else a committed dist/build/out/public.
            let publish = publish.or_else(|| {
                if dir.join("index.html").is_file() {
                    return None;
                }
                PUBLISH_CANDIDATES.iter().find(|c| dir.join(c).join("index.html").is_file()).map(|c| c.to_string())
            });
            match &publish {
                Some(p) => {
                    if !dir.join(p).is_dir() {
                        return Err(Error::invalid(format!("publish directory '{p}' does not exist")));
                    }
                    df.line(format!("COPY {p}/ {NGINX_HTML}/"));
                }
                None => {
                    df.line(format!("COPY . {NGINX_HTML}/"));
                    // Never serve Ferry's own build files.
                    df.run(&[], &format!("rm -rf {NGINX_HTML}/Dockerfile.ferry* {NGINX_HTML}/.git"));
                }
            }
        }
    }
    df.line("EXPOSE 80");
    Ok(GeneratedDockerfile { contents: df.finish(), port_hint: Some(80) })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn project(files: &[(&str, &str)]) -> tempfile::TempDir {
        let d = tempfile::tempdir().unwrap();
        for (name, contents) in files {
            let p = d.path().join(name);
            if let Some(parent) = p.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(p, contents).unwrap();
        }
        d
    }

    fn gen_with(runtime: Runtime, files: &[(&str, &str)], opts: DockerfileOptions) -> Result<GeneratedDockerfile> {
        let d = project(files);
        generate(runtime, d.path(), &opts)
    }

    fn gen_ok(runtime: Runtime, files: &[(&str, &str)], opts: DockerfileOptions) -> String {
        match gen_with(runtime, files, opts) {
            Ok(g) => g.contents,
            Err(e) => panic!("generation failed: {e}"),
        }
    }

    fn has_line(df: &str, line: &str) -> bool {
        df.lines().any(|l| l.trim() == line)
    }

    fn pos(df: &str, needle: &str) -> usize {
        df.find(needle).unwrap_or_else(|| panic!("'{needle}' not found in:\n{df}"))
    }

    fn opts() -> DockerfileOptions {
        DockerfileOptions::default()
    }

    #[test]
    fn node_npm_ci_with_build_and_start_script() {
        let df = gen_ok(
            Runtime::Node,
            &[
                (
                    "package.json",
                    r#"{"engines":{"node":"20.x"},"scripts":{"build":"tsc","start":"node dist/index.js"}}"#,
                ),
                ("package-lock.json", "{}"),
            ],
            DockerfileOptions { build_arg_keys: vec!["API_KEY".into(), "PATH".into(), "BAD-KEY".into()], ..opts() },
        );
        assert!(has_line(&df, "FROM node:20-alpine"), "{df}");
        assert!(has_line(&df, "COPY package.json package-lock.json ./"), "{df}");
        assert!(has_line(&df, "RUN npm ci --include=dev --no-audit --no-fund"), "{df}");
        assert!(has_line(&df, "RUN npm run build"), "{df}");
        assert!(has_line(&df, r#"CMD ["npm","start"]"#), "{df}");
        assert!(has_line(&df, "ARG API_KEY"), "{df}");
        assert!(!df.contains("ARG PATH") && !df.contains("BAD-KEY"), "{df}");
        // manifests → install → source → NODE_ENV → build
        assert!(pos(&df, "COPY package.json") < pos(&df, "RUN npm ci"));
        assert!(pos(&df, "RUN npm ci") < pos(&df, "COPY . ."));
        assert!(pos(&df, "RUN npm ci") < pos(&df, "ENV NODE_ENV=production"));
        assert!(pos(&df, "ENV NODE_ENV=production") < pos(&df, "RUN npm run build"));
        assert!(pos(&df, "ARG API_KEY") < pos(&df, "RUN npm ci"));
    }

    #[test]
    fn node_package_managers() {
        let yarn = gen_ok(
            Runtime::Node,
            &[("package.json", r#"{"main":"server.js"}"#), ("yarn.lock", ""), ("server.js", "")],
            opts(),
        );
        assert!(yarn.contains("corepack enable"), "{yarn}");
        assert!(has_line(&yarn, "RUN yarn install --frozen-lockfile --production=false"), "{yarn}");
        assert!(has_line(&yarn, r#"CMD ["node","server.js"]"#), "{yarn}");

        let berry = gen_ok(
            Runtime::Node,
            &[
                ("package.json", r#"{"packageManager":"yarn@4.1.0","scripts":{"start":"node x.js"}}"#),
                ("yarn.lock", "__metadata:\n  version: 8\n"),
                (".yarnrc.yml", "nodeLinker: node-modules\n"),
                (".yarn/releases/yarn.cjs", ""),
            ],
            opts(),
        );
        assert!(has_line(&berry, "RUN yarn install --immutable"), "{berry}");
        assert!(has_line(&berry, "COPY .yarn ./.yarn"), "{berry}");
        assert!(has_line(&berry, r#"CMD ["yarn","start"]"#), "{berry}");

        let pnpm = gen_ok(
            Runtime::Node,
            &[("package.json", r#"{"scripts":{"build":"vite build","start":"node s.js"}}"#), ("pnpm-lock.yaml", "")],
            opts(),
        );
        assert!(pnpm.contains("corepack enable"), "{pnpm}");
        assert!(has_line(&pnpm, "RUN pnpm install --frozen-lockfile"), "{pnpm}");
        assert!(has_line(&pnpm, "RUN pnpm run build"), "{pnpm}");

        let bun = gen_ok(
            Runtime::Node,
            &[("package.json", r#"{"scripts":{"start":"bun x.ts"}}"#), ("bun.lockb", "")],
            opts(),
        );
        assert!(has_line(&bun, "FROM oven/bun:1-alpine"), "{bun}");
        assert!(has_line(&bun, "RUN bun install"), "{bun}");
        assert!(has_line(&bun, r#"CMD ["bun","run","start"]"#), "{bun}");

        let npm = gen_ok(Runtime::Node, &[("package.json", "{}"), ("index.js", "")], opts());
        assert!(has_line(&npm, "RUN npm install --include=dev --no-audit --no-fund"), "{npm}");
        assert!(has_line(&npm, "FROM node:22-alpine"), "{npm}");
        assert!(has_line(&npm, r#"CMD ["node","index.js"]"#), "{npm}");
        assert!(!npm.contains("run build"), "{npm}");
    }

    #[test]
    fn node_start_resolution() {
        // start_command wins, in shell form (so $PORT expands)
        let df = gen_ok(
            Runtime::Node,
            &[("package.json", r#"{"scripts":{"start":"node a.js"}}"#), ("Procfile", "web: node web.js")],
            DockerfileOptions { start_command: Some("node x.js --port $PORT".into()), ..opts() },
        );
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","node x.js --port $PORT"]"#), "{df}");
        // Procfile before the start script
        let df = gen_ok(
            Runtime::Node,
            &[
                ("package.json", r#"{"scripts":{"start":"node a.js"}}"#),
                ("Procfile", "web: node web.js\nworker: node w.js"),
            ],
            opts(),
        );
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","node web.js"]"#), "{df}");
        let df = gen_ok(
            Runtime::Node,
            &[("package.json", "{}"), ("Procfile", "web: node web.js\nworker: node w.js")],
            DockerfileOptions { service_type: Some(ServiceType::BackgroundWorker), ..opts() },
        );
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","node w.js"]"#), "{df}");
        // main field
        let df = gen_ok(Runtime::Node, &[("package.json", r#"{"main":"lib/main.js"}"#), ("lib/main.js", "")], opts());
        assert!(has_line(&df, r#"CMD ["node","lib/main.js"]"#), "{df}");
        // nothing → helpful error
        let err = gen_with(Runtime::Node, &[("package.json", "{}")], opts()).unwrap_err().to_string();
        assert!(err.contains("start command") && err.contains("Procfile"), "{err}");
        // cron jobs may omit it
        let df = gen_ok(
            Runtime::Node,
            &[("package.json", "{}")],
            DockerfileOptions { service_type: Some(ServiceType::CronJob), ..opts() },
        );
        assert!(!df.contains("CMD"), "{df}");
    }

    #[test]
    fn node_copies_everything_when_install_needs_it() {
        let df = gen_ok(
            Runtime::Node,
            &[
                ("package.json", r#"{"scripts":{"postinstall":"prisma generate","start":"node a"}}"#),
                ("package-lock.json", ""),
            ],
            opts(),
        );
        assert!(pos(&df, "COPY . .") < pos(&df, "RUN npm ci"), "{df}");
        let df = gen_ok(
            Runtime::Node,
            &[("package.json", r#"{"workspaces":["packages/*"],"scripts":{"start":"node a"}}"#)],
            opts(),
        );
        assert!(pos(&df, "COPY . .") < pos(&df, "RUN npm install"), "{df}");
        assert!(gen_with(Runtime::Node, &[("package.json", "{not json")], opts()).is_err());
    }

    #[test]
    fn multiline_commands_use_exec_form() {
        let df = gen_ok(
            Runtime::Node,
            &[("package.json", "{}")],
            DockerfileOptions {
                build_command: Some("echo one\necho two".into()),
                start_command: Some("node a.js\nFROM evil".into()),
                ..opts()
            },
        );
        assert!(has_line(&df, r#"RUN ["/bin/sh","-c","echo one\necho two"]"#), "{df}");
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","node a.js\nFROM evil"]"#), "{df}");
        assert!(!df.lines().any(|l| l.starts_with("FROM evil")), "{df}");
    }

    #[test]
    fn python_variants() {
        let df = gen_ok(
            Runtime::Python,
            &[("requirements.txt", "flask\n"), ("app.py", ""), (".python-version", "3.11.6\n")],
            DockerfileOptions { build_arg_keys: vec!["SECRET".into()], ..opts() },
        );
        assert!(has_line(&df, "FROM python:3.11-slim"), "{df}");
        assert!(df.contains("PYTHONUNBUFFERED=1"), "{df}");
        assert!(has_line(&df, "COPY requirements.txt ./"), "{df}");
        assert!(has_line(&df, "RUN pip install --no-cache-dir -r requirements.txt"), "{df}");
        assert!(has_line(&df, r#"CMD ["python","app.py"]"#), "{df}");
        assert!(pos(&df, "ARG SECRET") < pos(&df, "RUN pip install"), "{df}");

        let df = gen_ok(
            Runtime::Python,
            &[("pyproject.toml", ""), ("main.py", ""), ("runtime.txt", "python-3.10.2")],
            opts(),
        );
        assert!(has_line(&df, "FROM python:3.10-slim"), "{df}");
        assert!(has_line(&df, "RUN pip install --no-cache-dir ."), "{df}");
        assert!(pos(&df, "COPY . .") < pos(&df, "RUN pip install"), "{df}");
        assert!(has_line(&df, r#"CMD ["python","main.py"]"#), "{df}");

        let df = gen_ok(
            Runtime::Python,
            &[("Pipfile", ""), ("Pipfile.lock", "{}"), ("Procfile", "web: gunicorn app:app -b 0.0.0.0:$PORT")],
            opts(),
        );
        assert!(has_line(&df, "FROM python:3.12-slim"), "{df}");
        assert!(df.contains("pipenv install --system --deploy"), "{df}");
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","gunicorn app:app -b 0.0.0.0:$PORT"]"#), "{df}");

        let df =
            gen_ok(Runtime::Python, &[("requirements.txt", "-r base.txt\n"), ("base.txt", ""), ("app.py", "")], opts());
        assert!(pos(&df, "COPY . .") < pos(&df, "RUN pip install"), "{df}");

        let err = gen_with(Runtime::Python, &[("requirements.txt", "")], opts()).unwrap_err().to_string();
        assert!(err.contains("start command"), "{err}");
    }

    #[test]
    fn go_variants() {
        let df = gen_ok(
            Runtime::Go,
            &[("go.mod", "module x\n\ngo 1.22.1\n"), ("go.sum", ""), ("main.go", "package main")],
            DockerfileOptions { build_arg_keys: vec!["GOPRIVATE".into()], ..opts() },
        );
        assert!(has_line(&df, "FROM golang:1.22-alpine AS build"), "{df}");
        assert!(has_line(&df, "COPY go.mod go.sum ./"), "{df}");
        assert!(df.contains("go mod download"), "{df}");
        assert!(df.contains("CGO_ENABLED=0 go build") && df.contains("-o /out/app ."), "{df}");
        assert!(has_line(&df, "FROM alpine:3.20"), "{df}");
        assert!(df.contains("ca-certificates"), "{df}");
        assert!(has_line(&df, r#"CMD ["/usr/local/bin/app"]"#), "{df}");
        assert!(has_line(&df, "ARG GOPRIVATE"), "{df}");

        let df = gen_ok(
            Runtime::Go,
            &[("go.mod", "module x\n"), ("cmd/server/main.go", "package main")],
            DockerfileOptions {
                build_command: Some("go build -o /out/srv ./cmd/server".into()),
                start_command: Some("srv --port $PORT".into()),
                ..opts()
            },
        );
        assert!(has_line(&df, "FROM golang:1.23-alpine AS build"), "{df}");
        assert!(df.contains("( go build -o /out/srv ./cmd/server )"), "{df}");
        assert!(!df.contains("CGO_ENABLED=0 go build"), "{df}");
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","srv --port $PORT"]"#), "{df}");

        let df = gen_ok(Runtime::Go, &[("go.mod", "module x\n"), ("cmd/api/main.go", "package main")], opts());
        assert!(df.contains("-o /out/app ./cmd/api"), "{df}");
        assert!(df.contains("RUN --mount=type=cache,target=/go/pkg/mod \\\n    --mount=type=cache,target=/root/.cache/go-build \\\n    mkdir -p /out && CGO_ENABLED=0"), "{df}");

        // A comment in a chained user command must not swallow the rest of the chain.
        let df = gen_ok(
            Runtime::Go,
            &[("go.mod", "module x\n"), ("main.go", "package main")],
            DockerfileOptions { build_command: Some("go build -o /out/app . # static".into()), ..opts() },
        );
        assert!(df.contains(r#"["/bin/sh","-c","set -e\nmkdir -p /out\ngo build -o /out/app . # static\n"]"#), "{df}");
    }

    #[test]
    fn rust_variants() {
        let df = gen_ok(
            Runtime::Rust,
            &[
                ("Cargo.toml", "[package]\nname = \"web-api\"\nversion = \"0.1.0\"\n"),
                ("Cargo.lock", "[[package]]\nname = \"openssl-sys\"\n"),
                ("src/main.rs", "fn main() {}"),
            ],
            opts(),
        );
        assert!(has_line(&df, "FROM rust:1-slim-bookworm AS build"), "{df}");
        assert!(df.contains("cargo build --release"), "{df}");
        assert!(df.contains("cp target/release/web-api /out/"), "{df}");
        assert!(has_line(&df, "FROM debian:bookworm-slim"), "{df}");
        assert!(df.contains("libssl-dev") && df.contains("libssl3"), "{df}");
        assert!(has_line(&df, r#"CMD ["/usr/local/bin/web-api"]"#), "{df}");

        let df = gen_ok(
            Runtime::Rust,
            &[("Cargo.toml", "[package]\nname = \"x\"\n\n[[bin]]\nname = \"srv\"\npath = \"src/srv.rs\"\n")],
            opts(),
        );
        assert!(df.contains("cp target/release/srv /out/"), "{df}");
        assert!(!df.contains("libssl"), "{df}");

        let err = gen_with(Runtime::Rust, &[("Cargo.toml", "[workspace]\nmembers = [\"a\"]\n")], opts()).unwrap_err();
        assert!(err.to_string().contains("start command"), "{err}");
        let df = gen_ok(
            Runtime::Rust,
            &[("Cargo.toml", "[workspace]\nmembers = [\"a\"]\n")],
            DockerfileOptions { start_command: Some("api".into()), ..opts() },
        );
        assert!(df.contains("find target/release -maxdepth 1"), "{df}");
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","api"]"#), "{df}");
    }

    #[test]
    fn ruby_variants() {
        let df = gen_ok(
            Runtime::Ruby,
            &[("Gemfile", "source 'https://rubygems.org'\ngem 'rack'\n"), ("Gemfile.lock", ""), ("config.ru", "")],
            opts(),
        );
        assert!(has_line(&df, "FROM ruby:3.3-slim"), "{df}");
        assert!(df.contains("build-essential"), "{df}");
        assert!(has_line(&df, "COPY Gemfile Gemfile.lock ./"), "{df}");
        assert!(has_line(&df, "RUN bundle install"), "{df}");
        assert!(df.contains(r#"CMD ["/bin/sh","-c","bundle exec rackup -o 0.0.0.0 -p ${PORT:-10000}"]"#), "{df}");

        let df = gen_ok(
            Runtime::Ruby,
            &[("Gemfile", "ruby '3.2.2'\n"), ("Procfile", "web: bundle exec puma -p $PORT")],
            opts(),
        );
        assert!(has_line(&df, "FROM ruby:3.2-slim"), "{df}");
        assert!(has_line(&df, r#"CMD ["/bin/sh","-c","bundle exec puma -p $PORT"]"#), "{df}");

        let err = gen_with(Runtime::Ruby, &[("Gemfile", "")], opts()).unwrap_err().to_string();
        assert!(err.contains("config.ru"), "{err}");
    }

    #[test]
    fn static_plain_and_publish_dir() {
        let g = gen_with(Runtime::Static, &[("index.html", "<h1>hi</h1>")], opts()).unwrap();
        assert_eq!(g.port_hint, Some(80));
        let df = g.contents;
        assert!(has_line(&df, "FROM nginx:alpine"), "{df}");
        assert!(has_line(&df, "COPY . /usr/share/nginx/html/"), "{df}");
        assert!(df.contains("try_files $uri $uri/ $uri.html =404;"), "{df}");
        assert!(df.contains("listen 80;") && df.contains("gzip on;"), "{df}");
        assert!(df.contains("root /usr/share/nginx/html;"), "{df}");
        assert!(!df.contains("node:"), "{df}");

        let df = gen_ok(
            Runtime::Static,
            &[("site/index.html", "")],
            DockerfileOptions { publish_dir: Some("./site/".into()), ..opts() },
        );
        assert!(has_line(&df, "COPY site/ /usr/share/nginx/html/"), "{df}");

        let err = gen_with(Runtime::Static, &[], DockerfileOptions { publish_dir: Some("nope".into()), ..opts() });
        assert!(err.unwrap_err().to_string().contains("does not exist"));
        let err = gen_with(Runtime::Static, &[], DockerfileOptions { publish_dir: Some("../x".into()), ..opts() });
        assert!(err.is_err());
        let err = gen_with(Runtime::Static, &[], DockerfileOptions { publish_dir: Some("a;rm -rf".into()), ..opts() });
        assert!(err.is_err());
    }

    #[test]
    fn static_with_node_build() {
        let g = gen_with(
            Runtime::Node,
            &[("package.json", r#"{"scripts":{"build":"vite build"}}"#), ("package-lock.json", "")],
            DockerfileOptions {
                service_type: Some(ServiceType::StaticSite),
                build_arg_keys: vec!["VITE_API".into()],
                ..opts()
            },
        )
        .unwrap();
        assert_eq!(g.port_hint, Some(80));
        let df = g.contents;
        assert!(has_line(&df, "FROM node:22-alpine AS build"), "{df}");
        assert!(has_line(&df, "RUN npm ci --include=dev --no-audit --no-fund"), "{df}");
        assert!(has_line(&df, "RUN npm run build"), "{df}");
        assert!(df.contains("for d in dist build out public"), "{df}");
        assert!(has_line(&df, "FROM nginx:alpine"), "{df}");
        assert!(has_line(&df, "COPY --from=build /ferry-publish/ /usr/share/nginx/html/"), "{df}");
        assert!(pos(&df, "ARG VITE_API") < pos(&df, "RUN npm run build"), "{df}");
        assert!(pos(&df, "FROM node:22-alpine AS build") < pos(&df, "FROM nginx:alpine"), "{df}");

        let df = gen_ok(
            Runtime::Static,
            &[("package.json", r#"{"scripts":{"build":"x"}}"#)],
            DockerfileOptions { publish_dir: Some("public/out".into()), ..opts() },
        );
        assert!(df.contains("if [ -d \"public/out\" ]"), "{df}");

        // package.json without a build script: served as-is
        let df = gen_ok(Runtime::Static, &[("package.json", "{}"), ("index.html", "")], opts());
        assert!(!df.contains("AS build"), "{df}");
        assert!(has_line(&df, "COPY . /usr/share/nginx/html/"), "{df}");

        // No build and no root index.html: a committed output dir is served.
        let df = gen_ok(Runtime::Static, &[("public/index.html", ""), ("README.md", "")], opts());
        assert!(has_line(&df, "COPY public/ /usr/share/nginx/html/"), "{df}");
        // ...but a root index.html wins over asset folders.
        let df = gen_ok(Runtime::Static, &[("index.html", ""), ("public/index.html", "")], opts());
        assert!(has_line(&df, "COPY . /usr/share/nginx/html/"), "{df}");

        // explicit build command without package.json
        let df = gen_ok(
            Runtime::Static,
            &[("build.sh", "")],
            DockerfileOptions { build_command: Some("sh build.sh".into()), publish_dir: Some("dist".into()), ..opts() },
        );
        assert!(df.contains("AS build") && has_line(&df, "RUN sh build.sh"), "{df}");
    }

    #[test]
    fn unsupported_runtimes() {
        let d = tempfile::tempdir().unwrap();
        assert!(generate(Runtime::Docker, d.path(), &opts()).is_err());
        assert!(generate(Runtime::Image, d.path(), &opts()).is_err());
        assert!(generate(Runtime::Auto, d.path(), &opts()).is_err());
        let d = project(&[("index.html", "")]);
        assert_eq!(generate(Runtime::Auto, d.path(), &opts()).unwrap().port_hint, Some(80));
    }

    #[test]
    fn build_arg_names() {
        assert!(usable_build_arg("NODE_ENV"));
        assert!(usable_build_arg("_X1"));
        assert!(!usable_build_arg("1X"));
        assert!(!usable_build_arg("A-B"));
        assert!(!usable_build_arg("A B"));
        assert!(!usable_build_arg(""));
        assert!(!usable_build_arg("PATH"));
        assert!(!usable_build_arg("DOCKER_HOST"));
        assert!(!usable_build_arg("BUILDKIT_INLINE_CACHE"));
    }
}
